# Generated by Django 4.2.7 on 2024-05-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='limitation_age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
