# Generated by Django 5.0.6 on 2024-07-21 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='file_came',
            new_name='file_game',
        ),
        migrations.AddField(
            model_name='games',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.CreateModel(
            name='ViewsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses_session', models.CharField(max_length=80)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.games')),
            ],
        ),
    ]
