# Generated by Django 5.0.6 on 2024-07-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_viewsgame_uses_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewsgame',
            old_name='uses_session',
            new_name='user_session',
        ),
    ]
