# Generated by Django 4.2.13 on 2024-06-04 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0006_products_file_came'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagsgame',
            options={'verbose_name': 'Тег или под категория', 'verbose_name_plural': 'Теги или под категории'},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/image_account/', verbose_name='Аватарка пользователя')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Телефон')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль которая привязывает пользователя')),
            ],
        ),
    ]
