# Generated by Django 5.0.6 on 2024-07-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_city_order_orderproduct_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(default=1, max_length=200, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
